"""coding.ai: Unified LLM API with multi-provider support."""

from coding.ai.env import get_env_api_key
from coding.ai.events import (
    AssistantMessageEventStream,
    EventStream,
    create_assistant_message_event_stream,
)
from coding.ai.models import (
    calculate_cost,
    get_model,
    get_models,
    get_providers,
    models_are_equal,
    register_models,
    supports_xhigh,
)
from coding.ai.models_builtin import register_builtin_models
from coding.ai.providers.builtins import register_builtin_providers
from coding.ai.registry import (
    ApiProvider,
    clear_api_providers,
    get_api_provider,
    get_api_providers,
    register_api_provider,
    unregister_api_providers,
)
from coding.ai.stream import complete, complete_simple, stream, stream_simple
from coding.ai.types import (
    AssistantMessage,
    AssistantMessageEvent,
    CacheRetention,
    Context,
    DoneEvent,
    ErrorEvent,
    ImageContent,
    Message,
    Model,
    ModelCost,
    SimpleStreamOptions,
    StartEvent,
    StopReason,
    StreamOptions,
    TextContent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingBudgets,
    ThinkingContent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingLevel,
    ThinkingStartEvent,
    Tool,
    ToolCall,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolResultMessage,
    Usage,
    UsageCost,
    UserMessage,
)
from coding.ai.vendors import VendorPreset, get_vendor_preset, get_vendor_presets

# Auto-register built-in providers and models on import
register_builtin_providers()
register_builtin_models()

__all__ = [
    "ApiProvider",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "CacheRetention",
    "Context",
    "DoneEvent",
    "ErrorEvent",
    "EventStream",
    "ImageContent",
    "Message",
    "Model",
    "ModelCost",
    "SimpleStreamOptions",
    "StartEvent",
    "StopReason",
    "StreamOptions",
    "TextContent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingBudgets",
    "ThinkingContent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingLevel",
    "ThinkingStartEvent",
    "Tool",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolResultMessage",
    "Usage",
    "UsageCost",
    "UserMessage",
    "VendorPreset",
    "calculate_cost",
    "clear_api_providers",
    "complete",
    "complete_simple",
    "create_assistant_message_event_stream",
    "get_api_provider",
    "get_api_providers",
    "get_env_api_key",
    "get_model",
    "get_models",
    "get_providers",
    "get_vendor_preset",
    "get_vendor_presets",
    "models_are_equal",
    "register_api_provider",
    "register_builtin_models",
    "register_builtin_providers",
    "register_models",
    "stream",
    "stream_simple",
    "supports_xhigh",
    "unregister_api_providers",
]
